def exr_to_jpg(exr_path: str, jpg_path: str, resize_width: int) -> None: ...
def hdr_to_jpg(hdr_path: str, jpg_path: str, resize_width: int) -> None: ...
def sdr_to_jpg(path: str, jpg_path: str, resize_width: int) -> None: ...
def apply_srgb_gamma(path: str) -> None: ...
def screenshot(
    output: str, x: int, y: int, width: int, height: int, resize_width: int
) -> None: ...
